def _exception_raise(self):
    '\n        Raises a pending exception that was recorded while getting a\n        Task ready for execution.\n        '
    exc = self.exc_info()[:]
    try:
        (exc_type, exc_value, exc_traceback) = exc
    except ValueError:
        (exc_type, exc_value) = exc
        exc_traceback = None
    raise exc_type, exc_value, exc_traceback
